Milestone 1: Header Section
yetemegn-telaye/My-Portfolio pull request #1
Opened 2022-08-18 10:12 UTC by yetemegn-telaye

## My Portfolio milestone 1: Header Section

In this milestone we:
- Created the toolbar section
- Created Headline section

2022-08-18 11:59 UTC, codecaiine requested changes
Hi @yetemegn-telaye , 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!
<FEEL FREE TO CHANGE THIS MESSAGE TO YOUR PERSONAL WORDS>

## Highlights
- Good use of github flow :heavy_check_mark: 
- Descriptive PR :heavy_check_mark: 
- No linters errors

## Required Changes ♻️

#### Please apply this requirement below because I can not use inline comments .
- [ ] Your license link is broken, Please don't forget to add a license to your project and I recommend using the [MIT license](https://choosealicense.com/licenses/mit/), Set it up quickly by [using templates available on GitHub](https://docs.github.com/en/communities/setting-up-your-project-for-healthy-contributions/adding-a-license-to-a-repository). another resource is [any other license](https://choosealicense.com/licenses/) . :smile: 
- [ ] Please remove all unnecessary information from your readme file and keep only main header you need in order to make it more professional :+1: 
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me (@codecaiine) in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-08-18 11:59 UTC, codecaiine commented on index.html
> +        <p>John Doe</p>
- [ ] From the project requirements this part which represents your website logo should be inside a link  `<a>` tag for the convention, and semantics reasons. Please fix it :+1:

2022-08-18 11:59 UTC, codecaiine commented on index.html
> +    <nav>
- [ ] For this section I would like to recommend you use `header` tag instead of `nav` because the header tag is used as a page header :+1:

2022-08-18 11:59 UTC, codecaiine commented on index.html
> +        </div>
- [ ] I would like to recommend you to use `<nav>` instead of div for this part and `<ul> <li>` tags for your menu options (**Portfolio/About/Contact**) Because use the `<nav>, <ul>, <li>` tags when building a navigation menu is that semantic markup will improve accessibility for users that require screen-readers. Please do it. :+1:

2022-08-18 11:59 UTC, codecaiine commented on index.html
> +    <main>
- [ ] Please ensure that all The container of the section is inside the `section` tag which means using the `section` tag instead of `main` because it represents a generic standalone section of the document, so use it. [Check this link](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/section) for more info:+1:

2022-08-18 11:59 UTC, codecaiine commented on index.html
> +                    <a><img src="images/social-icons/medium.svg" alt="medium icon"/></a>
- [ ] Please use a `ul` tag for your list of icons and group them, and use `li` per icon; each icon should be inside a link `a` tag . :+1:  It will make it semantically correct and  `a` tag will let you connect your social networks with the icons. Remember to add your href attribute in `a` tag . :+1:

2022-08-18 11:59 UTC, codecaiine commented on index.html
> +                    <h2>Hey There.<br/> I’m Alex</h2>
- [ ] Please ensure that your main title ("I'm Alex ...") is an `h1` tag. because If you want that google (and other search engines) knows about a specific topic, in this case, you, use an `h1` tag :smile:

2022-08-18 11:59 UTC, codecaiine commented on index.html
> +                    <span class="sub-title">I’am a Software Developer</span>
- [ ] Please use `p` tag instead of `span` for this part "I'm a software ..."  a `p` tag instead of `h1` because this way will be semantically correct and the screen readers :+1:

2022-08-18 11:59 UTC, codecaiine commented on index.html
> +    </main>
- [ ] Good job so far :+1:  You are doing a nice job but you need to address some issues :cry:  Please ensure that your section has the margins (top, bottom, left, right), background, and size as defined in the design. It's very important to much the design as much as possible so that your website will be pretty and works, it will be a wonderful website. :smile:  you can check the difference from the screenshots below :arrow_down: 

#### Figma design
![Screenshot from 2022-08-18 11-49-27](https://user-images.githubusercontent.com/6615394/185387829-0399a75a-2586-4d08-85ce-8f14319eb68f.png)

#### You design
![Screenshot from 2022-08-18 11-52-05](https://user-images.githubusercontent.com/6615394/185388263-3c552c03-5738-4d87-a55a-0282319f1b1c.png)

2022-08-19 00:21 UTC, mavericks-db approved these changes
Hi **@yetemegn-telaye**  😃 ,

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

![](https://media.giphy.com/media/3oz9ZE2Oo9zRC/giphy.gif)

## Highlights

- Have use the right GitHub flow ✅
- Meaningful title and summary for PR ✅
- Descriptive commit messages ✅
- Professional README.md file ✅
- Linter checks passed ✅

## Optional suggestions

- **[OPTIONAL]**

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Code review by **Mavericks De Leon Balitaan**

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-08-19 07:55 UTC, merged